### ISSUE TITLE
RangeError Array length must be a finite positive integer

### ISSUE THREAD

**Issue by mackwic** [sgmap/pix#61]
https://sentry.io/pix/pix-live/issues/161345445/

```
RangeError: Array length must be a finite positive integer
  at a.prototype.join (/assets/vendor-6b79cb010f8a8bae787cc7ef641f2b1a.js:3:30104)
  at u.join (/assets/vendor-6b79cb010f8a8bae787cc7ef641f2b1a.js:10:9784)
  at Anonymous function (/assets/vendor-6b79cb010f8a8bae787cc7ef641f2b1a.js:6:28279)
  at c (/assets/vendor-6b79cb010f8a8bae787cc7ef641f2b1a.js:9:16666)
  at Anonymous function (/assets/vendor-6b79cb010f8a8bae787cc7ef641f2b1a.js:6:28212)
...
(24 additional frame(s) were not displayed)
```

**Comment by bdavidxyz** [comment]
Issue too old, not related to current production environment
